apiVersion: v1
kind: Pod
metadata:
  name: my-pod-without-labels
spec:
  containers:
    - name: my-app-container
      image: nginx # You can replace this with your desired image
      ports:
        - name: http
          containerPort: 80 # Assuming your application inside the container listens on port 80
      readinessProbe:
        httpGet:
          path: / # Endpoint to check for readiness
          port: http
        initialDelaySeconds: 5 # Wait 5 seconds before first probe
        periodSeconds: 10 # Probe every 10 seconds
      livenessProbe:
        httpGet:
          path: / # Endpoint to check for liveness
          port: http
        initialDelaySeconds: 15 # Wait 15 seconds before first probe
        periodSeconds: 20 # Probe every 20 seconds
