apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      # This command keeps the container running so you can inspect it.     
      # The secrets will be available in the /etc/mysecret directory.       
      command: ['sh', '-c', 'echo "Secrets are mounted in /etc/mysecret. Listing contents:"; ls /etc/mysecret; echo "Pod will sleep now. Use kubectl exec to explore."; sleep 3600']
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/mysecret" # The path inside the container where secret data will be available                                               
          readOnly: true # It's good practice to mount secrets as read-only
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret # Replace 'my-secret' with the actual name of your Secret
        # Optional: If you want to mount only specific keys from the Secret,
you can use 'items':
# items:                                                            
# - key: username          # The key in your Secret                 
#   path: user.txt         # The filename it will appear as in /etc/mysecret
# - key: password                                                   
#   path: pass.txt           
