apiVersion: v1
kind: Pod
metadata:
  name: nginx-debian-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: debian-container
      image: debian
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: shared-data
          mountPath: /data
