apiVersion: v1
kind: Pod
metadata:
  name: my-sample-pod
  namespace: demo
  labels:
    app: my-app
spec:
  containers:
    - name: my-sample-container
      image: nginx # You can replace this with your desired image
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: / # Path to check for liveness
          port: http # Port name defined above
        initialDelaySeconds: 15 # Number of seconds after the container has started before liveness probes are initiated.
        periodSeconds: 20 # How often (in seconds) to perform the probe.
        timeoutSeconds: 5 # Number of seconds after which the probe times out.
        failureThreshold: 3 # When a probe fails, Kubernetes will try failureThreshold times before giving up.
